version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb_debts
    ports:
      - 27017:27017
  redis:
    container_name: redis_debts
    image: redis:alpine
    command: redis-server --requirepass docker
    ports:
      - 6379:6379
  web:
    build: ./web
    container_name: web_debts
    command: yarn start
    ports:
      - 3000:3000
  # app:
  #   build: .
  #   container_name: app_debts
  #   command: yarn start
  #   ports:
  #     - 3333:3333
  #   environment:
  #     - APP_SECRET=d1cc7d4ed609ea9b0d33f385efb05a4a614e9abc
  #     - ENVIRONMENT=stg
  #     - MONGO_URL=mongodb://root:root@localhost:27017/debts?retryWrites=true&w=majority
  #     # REDIS_URL: redis://:docker@localhost:6379
  #     - PORT=3333
  #   volumes:
  #     - ./src/
  #     # - nodemodules:/node_modules
  #   links:
  #     - mongodb
  #     - redis
  #   depends_on:
  #     - mongodb
  #     - redis
# volumes:
#   nodemodules: {}
