version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  app:
    build: .
    command: yarn dev
    ports:
      - 3333:3333
    environment:
      MONGO_URL: mongodb
      PORT: 3333
    environment:
      REDIS_URL: redis
      PORT: 3333
    volumes:
      - ./src/
      - nodemodules:/node_modules
    links:
      - mongodb
      - redis
    depends_on:
      - mongodb
      - redis

volumes:
  nodemodules: {}
